# Templates for linux, macOS, and Windows
# Based on approach from conda-forge

# skip pull requests
pr: none

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ./.azure-pipelines/download-source.yml
      parameters:
        flags: --use-conda
    - template: ./.azure-pipelines/download-conda.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ./.azure-pipelines/conda-win.yml
    - template: ./.azure-pipelines/conda-linux.yml
      parameters:
        distribution: centos
        version: [6]
    - template: ./.azure-pipelines/conda-osx.yml
      parameters:
        vmImage: [10, 14]
        xcode_version: [11, 3, 1]
